FROM python:3.10-slim

# instalar java (forma portable para debian moderno)
RUN apt-get update && \
    apt-get install -y default-jdk && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH="$JAVA_HOME/bin:$PATH"

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir \
    pyspark \
    pandas \
    pyarrow \
    google-cloud-bigquery \
    pandas-gbq \
    fsspec \
    gcsfs

CMD ["python", "spark_jobs/clean_rentals.py"]